name: sasa

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: action/checkout@v2
      -run : docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_UPASSWORD }}
      -run: docker build -t Shanab-debug -f Dockerfile.dev .