name: deploy react 

on: 
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t Shanab-debug/testt -f Dockerfile.dev .
      - run: docker run -e CI=true Shanab-debug/testt npm run test
      #kkkkk
      